import { readFileSync, writeFileSync } from "node:fs";

// Files bundled into llms-full.txt, in order. Keep in sync with the public surface.
const files = [
  "README.md",
  "CHANGELOG.md",
  "docs/API.md",
  "src/types.ts",
  "src/llms-text.ts",
  "src/llms-full.ts",
  "src/markdown-route.ts",
  "src/index.ts",
];

let out = `# @vllnt/next-llms — Full Source\n\nAuto-generated by \`pnpm generate:llms\`. Do not edit manually.\n`;

for (const f of files) {
  out += `\n---\n\n## ${f}\n\n`;
  if (f.endsWith(".md")) {
    out += readFileSync(f, "utf8");
  } else {
    out += "```ts\n" + readFileSync(f, "utf8") + "\n```";
  }
  out += "\n";
}

writeFileSync("llms-full.txt", out);
console.log(`Wrote llms-full.txt (${files.length} files)`);
